version: "3"
services: 
  redis: 
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - redis-net 
  backend:
    build: .
    ports:
      - "9090:9090"
    depends_on: 
      - redis
    networks:
      - redis-net
    restart: on-failure
    environment:
      - REDIS_ADDRESS=redis:6379
      - HTTP_ADDRESS=:9090
networks: 
  redis-net:
