version: "3"
services: 
  redis: 
    image: redis:alpine 
    ports:
      - "6379"
    networks:
      - redis-net 
  backend:
    image: helloapp
    ports:
      - "9090:9090"
    depends_on: 
      - redis
    networks:
      - redis-net
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090"]
      interval: 10s
      timeout: 5s
      retries: 3
networks: 
  redis-net:
